# Generated by Django 5.0.6 on 2024-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('not_sent', 'Not Sent Yet'), ('order_change', 'Order Change'), ('order_canceled', 'Order Canceled')], default='pending', max_length=20)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=225)),
                ('date', models.DateTimeField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
