# Generated by Django 5.0.6 on 2024-06-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customers_alter_order_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
