# Generated by Django 5.0.6 on 2024-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_customers_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orderpoints',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
